name: autonavi_maps_flutter
repository: https://github.com/walkunvs/autonavi-maps-flutter

packages:
  - packages/**
  - example

command:
  version:
    independentVersioning: true

scripts:
  analyze:
    exec: flutter analyze
    description: Analyze all packages

  test:
    exec: flutter test
    description: Run tests in all packages

  format:
    exec: dart format .
    description: Format all packages

  format_check:
    exec: dart format --output=none --set-exit-if-changed .
    description: Check formatting in all packages (CI)

  pub_get:
    exec: flutter pub get
    description: flutter pub get in all packages

  build_example_android:
    exec: flutter build apk --debug
    description: Build example Android APK
    packageFilters:
      dirExists: android
    select-package:
      scope: example

  build_example_ios:
    exec: flutter build ios --debug --no-codesign
    description: Build example iOS
    select-package:
      scope: example
